export const TALES = {
	start: 'tale/start',
  country1: 'tale/country1',
  rats: 'tale/rats',
  oldman: 'tale/oldman',
  insect: 'tale/insect',
  power: 'tale/power',
  kajit: 'tale/kajit',
  animal: 'tale/animal',
  country2: 'tale/country2',
  farmer: 'tale/farmer',
  country3: 'tale/country3',
  border: 'tale/border',
  money1: 'tale/money1',
  money2: 'tale/money2',
  money3: 'tale/money3',
  dwarf: 'tale/dwarf',
  princess1: 'tale/princess1',
  princess2: 'tale/princess2',
  princess3: 'tale/princess3',
  boss: 'tale/boss',
  finish: 'tale/finish'
};
